# Generated by Django 5.1.4 on 2025-01-11 15:40

import django.db.models.deletion
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='ImagenesEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=eventos.models.ImagenesEventos.imagen_ruta)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='eventos.eventos')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes de los eventos',
            },
        ),
    ]
