# Generated by Django 5.1.4 on 2025-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('politica', 'Política'), ('economia', 'Economía'), ('comunicado oficial', 'Comunicado Oficial'), ('deportes', 'Deportes'), ('cultura', 'Cultura'), ('tecnologia', 'Tecnología')], default='general', max_length=20, verbose_name='Tipo de Noticia'),
        ),
    ]
