# Generated by Django 5.1.4 on 2025-01-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticias_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='tipo',
            field=models.CharField(choices=[('General', 'General'), ('Politica', 'Política'), ('Economia', 'Economía'), ('Comunicado Oficial', 'Comunicado Oficial'), ('Deportes', 'Deportes'), ('Cultura', 'Cultura'), ('Tecnologia', 'Tecnología')], default='general', max_length=20, verbose_name='Tipo de Noticia'),
        ),
    ]
