# Generated by Django 5.1.4 on 2025-01-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_noticias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
