# Generated by Django 5.1.4 on 2025-01-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_alter_noticias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
